DROP SEQUENCE IF EXISTS SEQ_USER_CODE; 
CREATE SEQUENCE SEQ_USER_CODE INCREMENT BY
    1 MINVALUE 1 MAXVALUE 9999999 
START WITH
    1 NO CYCLE; 

DROP TABLE IF EXISTS M_USER CASCADE; 
CREATE TABLE M_USER( 
    PHONE_NUMBER VARCHAR (11)
    , USER_CODE VARCHAR (7)
    , USER_NAME VARCHAR (100)
    , EMAIL VARCHAR (100)
    , PASSWORD VARCHAR (60)
    , ROLE VARCHAR (4)
    , DELETE_FLAG VARCHAR (1)
    , CREATE_DATETIME TIMESTAMP
    , CREATE_USER_CODE VARCHAR (7)
    , UPDATE_DATETIME TIMESTAMP
    , UPDATE_USER_CODE VARCHAR (7)
    , PRIMARY KEY (PHONE_NUMBER)
); 

DROP SEQUENCE IF EXISTS SEQ_NEWS_CODE; 
CREATE SEQUENCE SEQ_NEWS_CODE INCREMENT BY
    1 MINVALUE 1 MAXVALUE 9999999 
START WITH
    1 NO CYCLE; 

DROP TABLE IF EXISTS NEWS CASCADE; 
CREATE TABLE NEWS( 
    NEWS_ID VARCHAR (7)
    , TITLE VARCHAR (100)
    , IMAGE_URL VARCHAR (1000)
    , WRITTEN_BY VARCHAR (100)
    , BODY VARCHAR (50000)
    , CREATE_DATETIME TIMESTAMP
    , CREATE_USER_CODE VARCHAR (7)
    , PRIMARY KEY (NEWS_ID)
); 

DROP SEQUENCE IF EXISTS SEQ_PROJECT_CODE; 
CREATE SEQUENCE SEQ_PROJECT_CODE INCREMENT BY
    1 MINVALUE 1 MAXVALUE 9999999 
START WITH
    1 NO CYCLE; 

DROP TABLE IF EXISTS PROJECTS CASCADE; 
CREATE TABLE PROJECTS( 
    PROJECTS_ID VARCHAR (7)
    , TITLE VARCHAR (1000)
    , ARCHITECT VARCHAR (100)
    , AREA VARCHAR (100)
    , YEAR VARCHAR (4)
    , IMAGE_URL VARCHAR (1000)
    , BODY VARCHAR (50000)
    , CREATE_DATETIME TIMESTAMP
    , CREATE_USER_CODE VARCHAR (7)
    , PRIMARY KEY (PROJECTS_ID)
); 

DROP TABLE IF EXISTS PACKAGE CASCADE; 
CREATE TABLE PACKAGE( 
    PACKAGE_ID VARCHAR (7)
    , PACKAGE_NAME VARCHAR (50)
    , UNIT_PRICE VARCHAR (12)
    , PRIMARY KEY (PACKAGE_ID)
); 

DROP TABLE IF EXISTS PACKAGE_DETAIL CASCADE; 
CREATE TABLE PACKAGE_DETAIL( 
    PACKAGE_ID VARCHAR (7)
    , DETAIL_NO VARCHAR (50)
    , IMAGE VARCHAR (1000)
    , PACKAGE_DETAIL_NAME VARCHAR (100)
    , DETAIL VARCHAR (500)
    , PRIMARY KEY (PACKAGE_ID, DETAIL_NO)
); 

DROP TABLE IF EXISTS package_type CASCADE; 
CREATE TABLE package_type( 
    PACKAGE_TYPE_ID VARCHAR (10)
    , PACKAGE_TYPE_NAME VARCHAR (50)
    , PRIMARY KEY (PACKAGE_TYPE_ID)
); 

DROP TABLE IF EXISTS package_type_detail CASCADE; 
CREATE TABLE package_type_detail( 
    PACKAGE_TYPE_ID VARCHAR (10)
    , DETAIL_NO VARCHAR (10)
    , TYPE_DETAIL_NAME VARCHAR (50)
    , COEFFICIENT VARCHAR (12)
    , PRIMARY KEY (PACKAGE_TYPE_ID, DETAIL_NO)
);

DROP TABLE IF EXISTS IMAGES CASCADE;
CREATE TABLE IMAGES(
    IMAGE_ID VARCHAR (7)
    , IMAGE_URL VARCHAR (1000)
    , PRIMARY KEY (IMAGE_ID)
);

DROP SEQUENCE IF EXISTS SEQ_QUOTE_CODE;

CREATE SEQUENCE SEQ_QUOTE_CODE INCREMENT BY
    1 MINVALUE 1 MAXVALUE 9999999
    START WITH
        1 NO CYCLE;

DROP TABLE IF EXISTS QUOTES CASCADE;

CREATE TABLE QUOTES(
    QUOTES_ID VARCHAR (7)
    , USER_NAME VARCHAR (100)
    , USER_PHONE_NUMBER VARCHAR (100)
    , PROJECT_LAND_AREA VARCHAR (100)
    , PROJECT_BUILD_AREA VARCHAR (100)
    , PROJECT_FLOOR VARCHAR (100)
    , SELECTED_PACKAGE VARCHAR (100)
    , UNIT_PRICE VARCHAR (100)
    , TOTAL_FLOOR_AREA VARCHAR (100)
    , TOTAL_PRICE VARCHAR (100)
    , CREATE_DATETIME TIMESTAMP
    , PRIMARY KEY (QUOTES_ID)
);
DROP TABLE IF EXISTS QUOTES_DETAIL CASCADE;

CREATE TABLE QUOTES_DETAIL(
    QUOTES_ID VARCHAR (7)
    , DETAIL_NO VARCHAR (7)
    , CATEGORY VARCHAR (100)
    , SELECTED_CATEGORY VARCHAR (100)
    , COEFFICIENT VARCHAR (100)
    , BUILD_AREA VARCHAR (100)
    , COST VARCHAR (100)
    , PRIMARY KEY (QUOTES_ID, DETAIL_NO)
);